global:
  owner: crmadrig@tibco.com
  qsname: quickstart-tibco-bwce
  regions:
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true

tests:
  quickstart-tibco-bwce:
    parameter_input: tibco-bwce-master-params.json
    template_file: tibco-bwce-master.template
